// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-2FGDp8sRkj5Dn-qCbj1R8t5PpccdFU',
    appId: '1:945655105377:web:9abedda8a49d073459a720',
    messagingSenderId: '945655105377',
    projectId: 'athar-b2247',
    authDomain: 'athar-b2247.firebaseapp.com',
    storageBucket: 'athar-b2247.appspot.com',
    measurementId: 'G-S9NV78VYCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCawuHpel4IR5Ftacil9WTQdY4MGtUfOfY',
    appId: '1:945655105377:android:993ca4ac28de74ef59a720',
    messagingSenderId: '945655105377',
    projectId: 'athar-b2247',
    storageBucket: 'athar-b2247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuI9Yqg4ThOVXuo_fR5b9y-jNFKjbfvsw',
    appId: '1:945655105377:ios:c2142df99602ff5b59a720',
    messagingSenderId: '945655105377',
    projectId: 'athar-b2247',
    storageBucket: 'athar-b2247.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuI9Yqg4ThOVXuo_fR5b9y-jNFKjbfvsw',
    appId: '1:945655105377:ios:068429837741b43f59a720',
    messagingSenderId: '945655105377',
    projectId: 'athar-b2247',
    storageBucket: 'athar-b2247.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
